apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterIssuer.keySecretRef }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: datalab-vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.clusterIssuer.keySecretRef }}
  data:
  - secretKey: {{ .Values.eabSecret.key }}
    remoteRef:
      key: {{ .Values.clusterIssuer.keySecretRef }} # the vault key has to have the same name as the secret
      property: SECTIGO_EAB_KEY
