apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for Prometheus deployment

type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: 78.2.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: oauth2-proxy
    version: 7.8.1
    repository: https://oauth2-proxy.github.io/manifests
    alias: oauth2proxy
  # - name: loki
  #   version: 6.42.0
  #   repository: https://grafana.github.io/helm-charts
  # - name: alloy
  #   version: 1.3.0
  #   repository: https://grafana.github.io/helm-charts
