apiVersion: v2
name: loki
description: A Helm chart for Kubernetes
type: application

version: 0.1.0


dependencies:
  - name: loki
    version: 6.42.0
    repository: https://grafana.github.io/helm-charts
  - name: alloy
    version: 1.3.0
    repository: https://grafana.github.io/helm-charts
