apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "existingSecret" }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: datalab-vault
    kind: ClusterSecretStore
  target:
    name: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "existingSecret" }}
  data:
  - secretKey: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "userKey" }}
    remoteRef:
      key: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "existingSecret" }}
      property: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "userKey" }}

  - secretKey: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "passwordKey" }}
    remoteRef:
      key: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "existingSecret" }}
      property: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "passwordKey" }}
  
