apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.oauth2proxy.config.existingSecret }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: datalab-vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.oauth2proxy.config.existingSecret }}
  data:
  - secretKey: client-id
    remoteRef:
      key: {{ .Values.oauth2proxy.config.existingSecret }}
      property: OAUTH2_PROXY_CLIENT_ID

  - secretKey: client-secret
    remoteRef:
      key: {{ .Values.oauth2proxy.config.existingSecret }}
      property: OAUTH2_PROXY_CLIENT_SECRET
  
  - secretKey: cookie-secret
    remoteRef:
      key: {{ .Values.oauth2proxy.config.existingSecret }}
      property: OAUTH2_PROXY_COOKIE_SECRET
