apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sso-client-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: datalab-vault
    kind: ClusterSecretStore
  target:
    name: sso-client-secret
  data:
  - secretKey: CLIENT_ID
    remoteRef:
      key: open-webui-sso-client-secret
      property: CLIENT_ID

  - secretKey: CLIENT_SECRET
    remoteRef:
      key: open-webui-sso-client-secret
      property: CLIENT_SECRET
